version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:5000/health
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
